import type { DrawingPerimeters } from "./drawing-object-perimeter";
import { pipeMeasuredWireLength } from "./drawing-dimensions";
import { resolveWireColorHex } from "./wire-reference-catalog";
import { Fragment, useState } from "react";
import { InfoHint } from "../InfoHint";
import type { EditorCommand } from "./commands";
import type { HarnessDesignDocument } from "./model";
import { addDrawingPositions, setDrawingPositionVisibility, moveDrawingAnnotation, buildDrawingBom, connectionEndLabel, drawingObjectOrigin, emptyDrawingDocuments, type DrawingDocuments } from "./drawing-documents";

export function DrawingDocumentsPanel({document,quantity,selectedId,selectedIds,onChange,onCommand,onReveal,mode="controls", perimeters, readOnly=false, availableKinds=["bom","connections","cut"]}: {
  perimeters?:DrawingPerimeters;readOnly?:boolean;availableKinds?:readonly ("bom"|"connections"|"cut")[];
  mode?:"controls"|"bom"|"connections";document:HarnessDesignDocument;quantity:number;selectedId:string|null;selectedIds:readonly string[];
  onChange:(d:DrawingDocuments)=>boolean;onCommand:(c:EditorCommand)=>boolean;onReveal:(ids:readonly string[])=>void;
}) {
  const [filter,setFilter]=useState("");
  const [onlyRelated,setOnlyRelated]=useState(false);
  const d=document.drawingDocuments ?? emptyDrawingDocuments(),rows=buildDrawingBom(document,quantity);
  const leader=d.leaders.find(l=>l.id===selectedId||`${l.id}:anchor`===selectedId);
  const addTable=(kind:"bom"|"connections"|"cut")=>onChange({...d,tables:[...d.tables,{id:crypto.randomUUID(),kind,position:{x:40+d.tables.length*30,y:40+d.tables.length*30}}]});
  const editBom=(key:string,field:"index"|"designation"|"name"|"note",value:string)=>onChange({...d,bomText:{...d.bomText,[key]:{...d.bomText?.[key],[field]:value}}});
  const updateLeader=(key:"anchorOffset"|"circle",axis:"x"|"y",value:number)=>{
    if(!leader)return; const point={...leader[key],[axis]:value};
    const origin=drawingObjectOrigin(document,leader.objectId);if(!origin)return;
    const docs=moveDrawingAnnotation(document,key==="circle"?leader.id:`${leader.id}:anchor`,key==="circle"?{x:point.x-12,y:point.y-12}:{x:origin.x+point.x-4,y:origin.y+point.y-4},perimeters);
    if(docs)onChange(docs);
  };
  const Content = mode === "controls" ? "details" : "div";
  return <section className="he-relations" aria-label={mode==="connections"?"Таблица соединений":"Документы схемы"}><Content className={mode!=="controls"?"he-document-content":undefined} {...(mode==="controls"?{open:!!leader}:{})}>{mode==="controls"&&<summary>{availableKinds.length===1?"Таблица соединений":"Таблицы и выноски"}</summary>}
    <header className="ui-section-heading"><InfoHint>{mode==="connections"||availableKinds.length===1 ? "Соединения взяты из текущего документа жгута. Фильтр не меняет данные. В Э4 и Чертеже таблицу можно открыть на поле, передвинуть и закрепить у края. В Маршруте доступен просмотр." : <>Количество спецификации рассчитано для всего количества жгутов. Фильтр меняет показ, но не расход. Кружок перемещается свободно, якорь — по периметру своего объекта; номер следует позиции спецификации. Таблицы на поле перетаскиваются за заголовок. «Добавить позиции» размещает все номера. Кнопка с глазом показывает или скрывает позицию сразу у всех её обозначений; новые номера располагаются рядом по горизонтали.</>}</InfoHint></header>
    {mode==="controls" && <div className="he-relations-actions">{availableKinds.map(kind=><button key={kind} className="ui-control" type="button" onClick={()=>addTable(kind)}>{kind==="bom"?"Спецификация +":kind==="cut"?"Резка +":"Соединения +"}</button>)}</div>}
    {mode==="controls" && d.tables.filter(t=>availableKinds.includes(t.kind)).map(t=><div className="he-relations-actions" key={t.id}><span>{t.kind==="bom"?"Спецификация":t.kind==="cut"?"Резка":"Соединения"}</span><button className="ui-control" type="button" onClick={()=>onChange({...d,tables:d.tables.filter(i=>i.id!==t.id)})}>Убрать с поля</button></div>)}
    {mode!=="controls" && <><div className="he-document-tools"><input aria-label="Поиск строки документа" placeholder="Поиск" value={filter} onChange={e=>setFilter(e.target.value)}/>
    <label><input type="checkbox" checked={onlyRelated} onChange={e=>setOnlyRelated(e.target.checked)}/>Только связанные</label>
    {mode==="bom" && <button className="ui-control" type="button" disabled={readOnly} onClick={()=>onChange(addDrawingPositions(document,perimeters))}>Добавить позиции</button>}{mode==="bom" && <small>Потребность на {quantity} жгут(а)</small>}</div>
    {mode==="bom" && <div className="he-document-table"><table aria-label="Спецификация"><thead><tr>{["Поз.","Индекс","Обозначение","Наименование","Кол-во","Примечание"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.filter(r=>(!onlyRelated||r.objectIds.some(id=>selectedIds.includes(id)))&&`${r.index} ${r.designation} ${r.name}`.toLocaleLowerCase().includes(filter.toLocaleLowerCase())).map(r=><tr key={r.key} className={r.objectIds.some(id=>selectedIds.includes(id))?"is-related":""}><td><button className="ui-control" type="button" onClick={()=>onReveal(r.objectIds)}>{r.position}</button><button className="ui-control he-position-toggle" type="button" disabled={readOnly||!r.objectIds.some(id=>drawingObjectOrigin(document,id))} aria-label={`${d.leaders.some(l=>l.rowKey===r.key&&!l.hidden)?"Скрыть":"Показать"} позицию ${r.position} у всех обозначений`} title="Показать / скрыть у всех обозначений" aria-pressed={d.leaders.some(l=>l.rowKey===r.key&&!l.hidden)} onClick={()=>onChange(setDrawingPositionVisibility(document,r.key,!d.leaders.some(l=>l.rowKey===r.key&&!l.hidden),perimeters))}><svg width="16" height="16" viewBox="0 0 20 20" aria-hidden="true"><path d="M2 10s3-5 8-5 8 5 8 5-3 5-8 5-8-5-8-5Z" fill="none" stroke="currentColor"/><circle cx="10" cy="10" r="2.5" fill="none" stroke="currentColor"/>{!d.leaders.some(l=>l.rowKey===r.key&&!l.hidden)&&<path d="m3 3 14 14" stroke="currentColor"/>}</svg></button></td><td><input readOnly={readOnly} aria-label={`Индекс позиции ${r.position}`} value={r.index} onChange={e=>editBom(r.key,"index",e.target.value)}/></td><td><input readOnly={readOnly} aria-label={`Обозначение позиции ${r.position}`} value={r.designation} onChange={e=>editBom(r.key,"designation",e.target.value)}/></td><td><input readOnly={readOnly} aria-label={`Наименование позиции ${r.position}`} value={r.name} onChange={e=>editBom(r.key,"name",e.target.value)}/></td><td>{r.amount ?? "—"} {r.unit}</td><td className="he-bom-note-cell"><input readOnly={readOnly} aria-label={`Примечание позиции ${r.position}`} value={r.note} onChange={e=>editBom(r.key,"note",e.target.value)}/><div className="he-relations-actions"><button className="ui-control" type="button" onClick={()=>{const i=rows.findIndex(row=>row.key===r.key),keys=rows.map(row=>row.key);if(i>0){[keys[i-1],keys[i]]=[keys[i]!,keys[i-1]!];onChange({...d,bomOrder:keys});}}}>↑</button></div>

    </td></tr>)}</tbody></table></div>}
    {mode==="connections" && <><div className="he-document-table"><table aria-label="Таблица соединений"><thead><tr><th rowSpan={2}>Провод</th><th colSpan={2}>Откуда</th><th colSpan={2}>Куда</th><th rowSpan={2}>Цепь</th><th rowSpan={2}>Длина, мм</th><th rowSpan={2}>Материал</th><th rowSpan={2}>Маршрут</th></tr><tr><th>Соединитель</th><th>Контакт</th><th>Соединитель</th><th>Контакт</th></tr></thead><tbody>{document.wires.filter(w=>(!onlyRelated||selectedIds.includes(w.id))&&`${w.circuit} ${connectionEndLabel(document,w.from)} ${connectionEndLabel(document,w.to)}`.toLowerCase().includes(filter.toLowerCase())).map(w=><tr key={w.id} className={selectedIds.includes(w.id)?"is-related":""}><td><button type="button" className="he-wire-row" title={w.id} onClick={()=>onReveal([w.id])}><i style={{background:resolveWireColorHex(w.color)}}/>{"W"+(document.wires.indexOf(w)+1)}</button></td>{[w.from,w.to].map((end,i)=>{const c=document.connectors.find(c=>c.id===end.connectorId),contact=c?.contacts.find(c=>c.id===end.contactId);return <Fragment key={i}><td>{c?c.designation+(c.partNumber?" ("+c.partNumber+")":""):connectionEndLabel(document,end)}</td><td>{contact?.number??"—"}</td></Fragment>;})}<td><input aria-label={`Цепь ${w.id}`} readOnly={readOnly} value={w.circuit} onChange={e=>onCommand({type:"update-wire",wireId:w.id,circuit:e.target.value})}/></td><td><input aria-label={`Длина ${w.id}`} title={pipeMeasuredWireLength(document,w.id).managed?"Длина по размерам пайпов; индивидуальные добавки — в поправках провода":undefined} readOnly={readOnly||pipeMeasuredWireLength(document,w.id).managed||document.drawingDocuments?.dimensions?.some(d=>d.wireId===w.id)} type="number" min="0" value={w.lengthMm ?? ""} onChange={e=>onCommand({type:"update-wire",wireId:w.id,lengthMm:e.target.value===""?null:Number(e.target.value)})}/></td><td>{w.materialBinding?.displayName ?? "—"}</td><td>{document.physicalTopology?.routes.find(r=>r.wireId===w.id)?.steps.length ? "Задан" : "Не задан"}</td></tr>)}</tbody></table></div></>}</>}
    {leader && <div className="he-physical-fields"><strong>Выноска</strong>{(["anchorOffset","circle"] as const).flatMap(key=>(["x","y"] as const).map(axis=><label key={`${key}${axis}`}>{key==="circle"?"Круг":"Якорь"} {axis}<input aria-label={`${key} ${axis}`} type="number" value={leader[key][axis]} onChange={e=>updateLeader(key,axis,Number(e.target.value))}/></label>))}<button className="ui-control" type="button" onClick={()=>onChange({...d,leaders:d.leaders.filter(l=>l.id!==leader.id)})}>Удалить выноску</button></div>}
    {d.leaders.filter(l=>!drawingObjectOrigin(document,l.objectId)||!rows.some(r=>r.key===l.rowKey&&r.objectIds.includes(l.objectId))).map(l=><small role="alert" key={l.id}>Выноска: объект или позиция отсутствует · {l.objectId}</small>)}
  </Content></section>;
}
