<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Techmap.Infrastructure.Sqlite/Techmap.Infrastructure.Sqlite.csproj" />
    <ProjectReference Include="../../src/Techmap.Infrastructure.Xlsx/Techmap.Infrastructure.Xlsx.csproj" />
    <ProjectReference Include="../../src/Techmap.Infrastructure.GoogleSheets/Techmap.Infrastructure.GoogleSheets.csproj" />
    <ProjectReference Include="../../src/Techmap.Web/Techmap.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../../src/Techmap.Client/index.html" Link="wwwroot/index.html" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
