<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefaultItemExcludes>$(DefaultItemExcludes);publish/**;.appdata/**;.dotnet-cli-home/**</DefaultItemExcludes>
    <AssemblyName>Techmap.Server</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="NuGet.Config" />
  </ItemGroup>
</Project>
