// Original worksheet headers/order from XlsxKnownProfiles.cs and docs/source-schema.md.
// Names are storage bindings, labels are the source's user-facing column names.
export interface ReferenceTableProfile {
  readonly title: string;
  readonly entityType: string;
  readonly columns: readonly { readonly name: string; readonly label: string }[];
}
export const referenceTableProfiles: Readonly<Record<string, ReferenceTableProfile>> = {
  "technology-operations": {
    title: "Операции",
    entityType: "operation",
    columns: [
      { name: "$sourceKey", label: "Номер" },
      { name: "name", label: "Название" },
      { name: "applicatorsModules", label: "Апликаторы / модули" },
      { name: "program", label: "Программа" },
      { name: "machine", label: "Машина" },
      { name: "semiFinishedProduct", label: "Полуфабрикат" },
      { name: "wire", label: "Провод" },
      { name: "connector", label: "Разъем" },
      { name: "tool", label: "Инструмент" },
      { name: "legacyOperationTime", label: "Время Операции" },
      { name: "setupTimeSeconds", label: "Время подготовки, сек" },
      { name: "setupConsumption", label: "Расход на настройку м; шт;" },
      { name: "legacyHumanTime", label: "Время Чел, сек/оп; сек/м" },
      { name: "legacyMachineTime", label: "Время машины, сек/оп; сек/м" },
      { name: "legacyHumanUnitPrice", label: "Уд.Цена ЧЛ, сек" },
      { name: "legacyHumanUnitPriceMag", label: "Уд.Цена ЧЛ_МАГ, сек" },
      { name: "legacyMachineUnitPrice", label: "Уд.Цена МШ, сек" },
      { name: "operationType", label: "Тип операции" },
      { name: "manualTakeTimeSeconds", label: "Время ручных работ для взятия полуфабриката" },
      { name: "manualWorkTimeSeconds", label: "Время ручных работ" },
      { name: "manualRemoveTimeSeconds", label: "Время ручных работ для снятия полуфабриката" },
      { name: "feedTimeSecondsPerMeter", label: "Скорость проката, сек/м" },
      { name: "toolCycleTimeSeconds", label: "Скорость работы инструмента" },
      { name: "toolOperationCount", label: "Кол-во операций инструмента" },
      { name: "additionalTimeSeconds", label: "Время доп.операции" },
      { name: "instruction", label: "Инструкция" },
      { name: "rejects", label: "Отказы" },
    ],
  },
  "technology-equipment": {
    title: "Оборудование",
    entityType: "equipment",
    columns: [
      { name: "ordinal", label: "№" },
      { name: "type", label: "Тип" },
      { name: "$sourceKey", label: "Инв. номер" },
      { name: "article", label: "Артикул" },
      { name: "name", label: "Наменование" },
      { name: "manufacturer", label: "Производитель" },
      { name: "operations", label: "Операции" },
      { name: "powerConsumption", label: "Потребление,вват/ч" },
      { name: "manufacturerUrl", label: "Ссылка на сайт производителя" },
      { name: "location", label: "Расположение" },
      { name: "description", label: "Описание" },
      { name: "machineLabel", label: "Для базы" },
      { name: "fullName", label: "Полное наименование" },
      { name: "cost", label: "Стоимость" },
      { name: "coefficient", label: "Коэффициент" },
      { name: "paybackMonths", label: "Cрок окупаемости, мес." },
      { name: "workSecondsPerMonth", label: "Кол-во сек. работы в мес." },
      { name: "targetPaybackSeconds", label: "Желаемый срок окупаемости, сек." },
      { name: "operationCostPerSecond", label: "Стоимость 1 сек. эксплуатации без НДС" },
      { name: "dimensions", label: "Габариты ШхД" },
    ],
  },
  "technology-terminals": {
    title: "Терминалы",
    entityType: "terminal",
    columns: [
      { name: "connectorType", label: "Тип разъема" },
      { name: "manufacturer", label: "Производитель" },
      { name: "productName", label: "Product Name" },
      { name: "series", label: "Series" },
      { name: "pitchMm", label: "Шаг разьема" },
      { name: "contactType", label: "Тип контакта" },
      { name: "reelArticle", label: "Артикул контакта (REEL)" },
      { name: "bagArticle", label: "Артикул контакта (BAG)" },
      { name: "applicator", label: "Аппликатор" },
      { name: "pneumaticAutomatic", label: "Пневма Автомат" },
      { name: "otr", label: "ОТР" },
      { name: "withStripping", label: "С зачисткой" },
      { name: "stripLengthMm", label: "Длина зачистки, мм" },
      { name: "lengthPlusMm", label: "L+" },
      { name: "lengthMinusMm", label: "L-" },
      { name: "conductorCrimpHeightMm", label: "Высота обжима проводника , мм" },
      { name: "insulationCrimpHeightMm", label: "Высота обжима изоляции, мм" },
      { name: "pullForceMinN", label: "Усилие обрыва контакта от, N" },
      { name: "pullForceMaxN", label: "Усилие обрыва контакта до, N" },
      { name: "awgFrom", label: "От AWG" },
      { name: "awgTo", label: "До AWG" },
      { name: "sectionFromMm2", label: "От мм2" },
      { name: "sectionToMm2", label: "До мм2" },
      { name: "insulationDiameterFromMm", label: "Диаметр изоляции от, мм" },
      { name: "insulationDiameterToMm", label: "Диаметр изоляции до, мм" },
      { name: "contactMaterial", label: "Материал контакта" },
      { name: "maximumCurrentA", label: "Максисмальная сила тока, А" },
      { name: "datasheetUrl", label: "Ссылка на DATASHEET на сайте производителя" },
    ],
  },
  "technology-coax-terminations": {
    title: "Разделка коаксиала",
    entityType: "coax-termination",
    columns: [
      { name: "legacyArticle", label: "Артикул" },
      { name: "typeSeries", label: "Тип/Серия" },
      { name: "cable", label: "Провод" },
      { name: "manufacturer", label: "Производитель" },
      { name: "program", label: "Программа" },
      { name: "layerD1", label: "D1" },
      { name: "layerD2", label: "D2" },
      { name: "layerD3", label: "D3" },
      { name: "layerL1", label: "L1" },
      { name: "layerL2", label: "L2" },
      { name: "layerL3", label: "L3" },
      { name: "lengthPlusMm", label: "L+" },
      { name: "lengthMinusMm", label: "L-" },
      { name: "pinType", label: "Тип пина" },
      { name: "shieldType", label: "Тип экрана" },
    ],
  },
  "technology-coax-cables": {
    title: "Коаксиальные кабели",
    entityType: "coax-cable",
    columns: [
      { name: "$sourceKey", label: "Кабель" },
      { name: "layerD1", label: "D1" },
      { name: "layerD2", label: "D2" },
      { name: "layerD3", label: "D3" },
    ],
  },
  "technology-awg-reference": {
    title: "Соответствие AWG и диаметров",
    entityType: "awg-reference",
    columns: [
      { name: "$sourceKey", label: "AWG" },
      { name: "sectionMm2", label: "ГОСТ" },
      { name: "conductorDiameterMm", label: "Ø жилы" },
      { name: "mgtfDiameterMm", label: "МГТФ" },
      { name: "msDiameterMm", label: "МС" },
      { name: "m22759DiameterMm", label: "M22759" },
      { name: "ptfeDiameterMm", label: "PTFE" },
      { name: "ul1061DiameterMm", label: "UL1061" },
      { name: "ul1571DiameterMm", label: "UL1571" },
      { name: "ul1007DiameterMm", label: "UL1007" },
      { name: "ul1015DiameterMm", label: "UL1015" },
      { name: "mgshvDiameterMm", label: "МГШВ" },
      { name: "nv4DiameterMm", label: "НВ-4" },
      { name: "siliconeDiameterMm", label: "Силикон" },
      { name: "rkgmDiameterMm", label: "РКГМ" },
      { name: "pvamDiameterMm", label: "ПВАМ" },
      { name: "pgvaDiameterMm", label: "ПГВА" },
      { name: "flryDiameterMm", label: "FLRY" },
      { name: "txlDiameterMm", label: "TXL" },
      { name: "gxlDiameterMm", label: "GXL" },
    ],
  },
};
